# Generated by Django 5.2.7 on 2025-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
